# Generated by Django 3.2.6 on 2021-08-23 21:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profil', '0008_alter_profil_biografija'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProsledjenRad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kada_poslat', models.DateField()),
                ('konacna_odluka', models.BooleanField()),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Rad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=125, unique=True)),
                ('kategorija', models.CharField(max_length=60)),
                ('opis', models.TextField()),
                ('clanovi', models.CharField(max_length=225)),
                ('godina', models.PositiveIntegerField(help_text='Use the following format: YYYY', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)])),
                ('biografije', models.TextField()),
                ('datum_podnosenja', models.DateField()),
                ('oblasti', models.ManyToManyField(to='profil.Oblast')),
                ('profil', models.ManyToManyField(through='radovi.ProsledjenRad', to='profil.Profil')),
            ],
        ),
        migrations.AddField(
            model_name='prosledjenrad',
            name='rad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radovi.rad'),
        ),
    ]
