# Generated by Django 3.2.6 on 2021-08-24 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programski_pozivi', '0003_alter_programskipoziv_naziv'),
        ('radovi', '0002_rad_programski_poziv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosledjenrad',
            name='kada_poslat',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prosledjenrad',
            name='konacna_odluka',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rad',
            name='programski_poziv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programski_pozivi.programskipoziv'),
        ),
    ]
