# Generated by Django 3.2.6 on 2021-08-12 19:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profil', '0002_profil_otvoren'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=125)),
                ('opis', models.TextField(blank=True)),
                ('oblast', models.ManyToManyField(to='profil.Oblast')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramskiPoziv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konacna_ocena', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('oblast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profil.oblast')),
            ],
        ),
        migrations.CreateModel(
            name='ProsledjenRad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kada_poslat', models.DateField()),
                ('konacna_odluka', models.BooleanField()),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Rad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=125, unique=True)),
                ('kategorija', models.CharField(max_length=60)),
                ('opis', models.TextField()),
                ('clanovi', models.CharField(max_length=225)),
                ('godina', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)])),
                ('biografije', models.TextField()),
                ('datum_podnosenja', models.DateField()),
                ('oblast', models.ManyToManyField(to='profil.Oblast')),
                ('profil', models.ManyToManyField(through='administrator.ProsledjenRad', to='profil.Profil')),
            ],
        ),
        migrations.AddField(
            model_name='prosledjenrad',
            name='rad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.rad'),
        ),
        migrations.CreateModel(
            name='ProgramskiPozivPitanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitanje', models.CharField(max_length=225)),
                ('odgovor', models.TextField()),
                ('programski_poziv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.programskipoziv')),
            ],
        ),
        migrations.AddField(
            model_name='programskipoziv',
            name='rad',
            field=models.ManyToManyField(to='administrator.Rad'),
        ),
        migrations.CreateModel(
            name='Obavestenje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=60, unique=True)),
                ('tekst', models.TextField()),
                ('datum_vreme_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('potpis', models.CharField(max_length=60)),
                ('profil', models.ManyToManyField(to='profil.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='AnketaPitanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitanje', models.CharField(max_length=225)),
                ('odgovor', models.TextField(blank=True)),
                ('ponudjeni_odgovor', models.SmallIntegerField(blank=True, choices=[(0, 'Slazem se'), (1, 'Ne slazem se'), (2, 'Ne znam')])),
                ('anketa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.anketa')),
            ],
        ),
    ]
