# Generated by Django 3.2.6 on 2021-08-30 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profil', '0008_alter_profil_biografija'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obavestenje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=60)),
                ('tekst', models.TextField()),
                ('datum_vreme_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('potpis', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Obrisanostanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrisano', models.BooleanField(default=False)),
                ('obavestenje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obavest', to='administrator.obavestenje')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korisnik', to='profil.profil')),
            ],
        ),
        migrations.AddField(
            model_name='obavestenje',
            name='profil',
            field=models.ManyToManyField(through='administrator.Obrisanostanje', to='profil.Profil'),
        ),
    ]
