# Generated by Django 3.2.6 on 2021-08-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20210813_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programskipoziv',
            name='rad',
        ),
    ]
