# Generated by Django 3.2.6 on 2021-08-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_programskipoziv_konacna_ocena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programskipozivpitanje',
            name='odgovor',
            field=models.TextField(blank=True),
        ),
    ]
