# Generated by Django 3.2.6 on 2021-08-20 20:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_alter_programskipozivpitanje_odgovor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programskipoziv',
            name='oblast',
        ),
        migrations.RemoveField(
            model_name='programskipozivpitanje',
            name='odgovor',
        ),
        migrations.RemoveField(
            model_name='programskipozivpitanje',
            name='programski_poziv',
        ),
        migrations.AddField(
            model_name='programskipoziv',
            name='naziv',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AddField(
            model_name='rad',
            name='programski_poziv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.programskipoziv'),
        ),
        migrations.AlterField(
            model_name='programskipoziv',
            name='konacna_ocena',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='ProgramskiPozivOdgovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odgovor', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pitanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.programskipozivpitanje')),
                ('programski_poziv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.programskipoziv')),
            ],
        ),
        migrations.AddField(
            model_name='programskipoziv',
            name='pitanje',
            field=models.ManyToManyField(through='administrator.ProgramskiPozivOdgovor', to='administrator.ProgramskiPozivPitanje'),
        ),
    ]
