# Generated by Django 3.2.6 on 2021-08-20 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20210820_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rad',
            name='programski_poziv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.programskipoziv'),
        ),
    ]
