# Generated by Django 3.2.6 on 2021-08-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20210823_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obavestenje',
            name='naslov',
            field=models.CharField(max_length=60),
        ),
    ]
