# Generated by Django 3.2.6 on 2021-08-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_alter_rad_programski_poziv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programskipoziv',
            name='pitanje',
        ),
        migrations.RemoveField(
            model_name='programskipozivodgovor',
            name='programski_poziv',
        ),
        migrations.AddField(
            model_name='programskipozivpitanje',
            name='programski_poziv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.programskipoziv'),
        ),
        migrations.AlterField(
            model_name='programskipoziv',
            name='naziv',
            field=models.CharField(max_length=125),
        ),
    ]
