# Generated by Django 3.2.6 on 2021-08-22 20:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20210822_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='programskipozivpitanje',
            name='odgovor',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='programskipozivpitanje',
            name='programski_poziv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.programskipoziv'),
        ),
        migrations.DeleteModel(
            name='ProgramskiPozivOdgovor',
        ),
    ]
