# Generated by Django 3.2.6 on 2021-08-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_auto_20210822_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosledjenrad',
            name='kada_poslat',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prosledjenrad',
            name='konacna_odluka',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
