# Generated by Django 3.2.6 on 2021-08-23 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_auto_20210823_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programskipozivpitanje',
            name='odgovor',
        ),
        migrations.CreateModel(
            name='ProgramskiPozivOdgovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odgovor', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pitanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.programskipozivpitanje')),
            ],
        ),
    ]
