# Generated by Django 3.2.6 on 2021-08-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_alter_profil_biografija'),
        ('administrator', '0012_auto_20210823_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='programskipozivodgovor',
            name='profil',
            field=models.ManyToManyField(to='profil.Profil'),
        ),
    ]
