# Generated by Django 3.2.6 on 2021-08-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_programskipozivodgovor_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programskipozivodgovor',
            name='pitanje',
        ),
        migrations.AddField(
            model_name='programskipozivodgovor',
            name='pitanje',
            field=models.ManyToManyField(to='administrator.ProgramskiPozivPitanje'),
        ),
    ]
