# Generated by Django 3.2.6 on 2021-08-23 21:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profil', '0008_alter_profil_biografija'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramskiPoziv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konacna_ocena', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('oblast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profil.oblast')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramskiPozivPitanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitanje', models.CharField(max_length=225)),
                ('odgovor', models.TextField(blank=True)),
                ('programski_poziv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programski_pozivi.programskipoziv')),
            ],
        ),
    ]
