# Generated by Django 3.2.6 on 2021-08-24 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_alter_profil_biografija'),
        ('programski_pozivi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programskipoziv',
            name='oblast',
        ),
        migrations.RemoveField(
            model_name='programskipozivpitanje',
            name='odgovor',
        ),
        migrations.AddField(
            model_name='programskipoziv',
            name='naziv',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AlterField(
            model_name='programskipoziv',
            name='konacna_ocena',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='ProgramskiPozivOdgovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odgovor', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pitanje', models.ManyToManyField(to='programski_pozivi.ProgramskiPozivPitanje')),
                ('profil', models.ManyToManyField(to='profil.Profil')),
            ],
        ),
    ]
