# Generated by Django 3.2.6 on 2021-08-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programski_pozivi', '0002_auto_20210824_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programskipoziv',
            name='naziv',
            field=models.CharField(max_length=125),
        ),
    ]
