# Generated by Django 3.2.6 on 2021-08-27 18:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_alter_profil_biografija'),
        ('programski_pozivi', '0003_alter_programskipoziv_naziv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramskiPozivOdgovori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odgovor1', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('odgovor2', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('odgovor3', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('odgovor4', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('odgovor5', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('odgovor6', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('odgovor7', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('odgovor8', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('odgovor9', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('odgovor10', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('ukupan_broj_poena', models.SmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.profil')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramskiPozivPitanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitanje1', models.CharField(max_length=225)),
                ('pitanje2', models.CharField(max_length=225)),
                ('pitanje3', models.CharField(max_length=225)),
                ('pitanje4', models.CharField(max_length=225)),
                ('pitanje5', models.CharField(max_length=225)),
                ('pitanje6', models.CharField(max_length=225)),
                ('pitanje7', models.CharField(max_length=225)),
                ('pitanje8', models.CharField(max_length=225)),
                ('pitanje9', models.CharField(max_length=225)),
                ('pitanje10', models.CharField(max_length=225)),
            ],
        ),
        migrations.RemoveField(
            model_name='programskipozivpitanje',
            name='programski_poziv',
        ),
        migrations.RemoveField(
            model_name='programskipoziv',
            name='konacna_ocena',
        ),
        migrations.AddField(
            model_name='programskipoziv',
            name='opis',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='ProgramskiPozivOdgovor',
        ),
        migrations.DeleteModel(
            name='ProgramskiPozivPitanje',
        ),
        migrations.AddField(
            model_name='programskipozivpitanja',
            name='programski_poziv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programski_pozivi.programskipoziv'),
        ),
        migrations.AddField(
            model_name='programskipozivodgovori',
            name='programski_poziv_pitanja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programski_pozivi.programskipozivpitanja'),
        ),
    ]
