# Generated by Django 3.2.6 on 2021-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programski_pozivi', '0004_auto_20210827_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programskipoziv',
            name='opis',
            field=models.TextField(),
        ),
    ]
