# Generated by Django 3.2.6 on 2021-08-11 12:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profil.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oblast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=30)),
                ('nacionalnost', models.CharField(max_length=30)),
                ('NIO', models.CharField(max_length=125)),
                ('naucno_zvanje', models.CharField(max_length=125, verbose_name='naucno zvanje')),
                ('angazovanje', models.CharField(max_length=125)),
                ('adresa', models.CharField(max_length=125)),
                ('broj_telefona', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('website', models.URLField(max_length=225)),
                ('biografija', models.FileField(upload_to='', validators=[profil.validators.validate_file_extension])),
                ('naucni_rad_1', models.CharField(max_length=125)),
                ('naucni_rad_2', models.CharField(max_length=125)),
                ('naucni_rad_3', models.CharField(max_length=125)),
                ('naucni_rad_4', models.CharField(max_length=125)),
                ('naucni_rad_5', models.CharField(max_length=125)),
                ('naucni_rad_6', models.CharField(max_length=125)),
                ('naucni_rad_7', models.CharField(max_length=125)),
                ('naucni_rad_8', models.CharField(max_length=125)),
                ('naucni_rad_9', models.CharField(max_length=125)),
                ('naucni_rad_10', models.CharField(max_length=125)),
                ('oblasti', models.ManyToManyField(to='profil.Oblast')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
