# Generated by Django 3.2.6 on 2021-08-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_profil_otvoren'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='otvoren',
            new_name='pregleda_se',
        ),
        migrations.AlterField(
            model_name='profil',
            name='website',
            field=models.URLField(blank=True, max_length=225),
        ),
    ]
