# Generated by Django 3.2.6 on 2021-08-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_auto_20210812_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='website',
            field=models.URLField(blank=True, max_length=225, null=True),
        ),
    ]
