# Generated by Django 3.2.6 on 2021-08-13 13:26

from django.db import migrations, models
import profil.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_alter_profil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='biografija',
            field=models.FileField(upload_to='PDF_files/', validators=[profil.validators.validate_file_extension]),
        ),
    ]
