# Generated by Django 3.2.6 on 2021-08-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_alter_profil_biografija'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='pregledane_ankete',
            field=models.IntegerField(default=0, verbose_name='broj pregledanih anketa'),
        ),
        migrations.AlterField(
            model_name='oblast',
            name='naziv',
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
