# Generated by Django 3.2.6 on 2021-08-23 21:32

from django.db import migrations, models
import profil.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_auto_20210814_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='biografija',
            field=models.FileField(upload_to='profil/pdfs', validators=[profil.validators.validate_file_extension]),
        ),
    ]
