# Generated by Django 3.2.6 on 2021-09-01 18:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profil', '0009_rename_pregledane_ankete_profil_popunjene_ankete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AnketaPopunjena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popunjena_anketa', models.BooleanField(default=False)),
                ('anketa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ankete.anketa')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.profil')),
            ],
        ),
        migrations.CreateModel(
            name='AnketaPitanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitanje_text', models.CharField(max_length=200)),
                ('opcija_one', models.CharField(max_length=30)),
                ('opcija_two', models.CharField(max_length=30)),
                ('opcija_three', models.CharField(max_length=30)),
                ('opcija_one_count', models.IntegerField(default=0)),
                ('opcija_two_count', models.IntegerField(default=0)),
                ('opcija_three_count', models.IntegerField(default=0)),
                ('anketa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ankete.anketa')),
            ],
        ),
        migrations.AddField(
            model_name='anketa',
            name='profil',
            field=models.ManyToManyField(blank=True, through='ankete.AnketaPopunjena', to='profil.Profil'),
        ),
    ]
