# Generated by Django 3.2.6 on 2021-08-23 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profil', '0008_alter_profil_biografija'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=125, unique=True)),
                ('opis', models.TextField(blank=True)),
                ('oblasti', models.ManyToManyField(to='profil.Oblast')),
            ],
        ),
        migrations.CreateModel(
            name='AnketaPitanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitanje', models.CharField(max_length=225)),
                ('odgovor', models.TextField(blank=True)),
                ('ponudjeni_odgovor', models.SmallIntegerField(blank=True, choices=[(0, 'Slazem se'), (1, 'Ne slazem se'), (2, 'Ne znam')], null=True)),
                ('anketa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ankete.anketa')),
            ],
        ),
    ]
